import React from "react";
import Wrapper from "./components/Wrapper";
import Title from "./components/Title";
import StudentCard from "./components/StudentCard";
import students from "./students.json";


function App() {
  return (
    <Wrapper>
      <Title>2020 Bootcamp Students</Title>
      <StudentCard
        name={students[0].name}
        image={students[0].image}
        occupation={students[0].occupation}
        location={students[0].location}
      />
      <StudentCard
        name={students[1].name}
        image={students[1].image}
        occupation={students[1].occupation}
        location={students[1].location}
      />
      <StudentCard
        name={students[2].name}
        image={students[2].image}
        occupation={students[2].occupation}
        location={students[2].location}
      />
      <StudentCard
        name={students[3].name}
        image={students[3].image}
        occupation={students[3].occupation}
        location={students[3].location}
      />
        <StudentCard
        name={students[4].name}
        image={students[4].image}
        occupation={students[4].occupation}
        location={students[4].location}
      />
        <StudentCard
        name={students[5].name}
        image={students[5].image}
        occupation={students[5].occupation}
        location={students[5].location}
      />
        <StudentCard
        name={students[6].name}
        image={students[6].image}
        occupation={students[6].occupation}
        location={students[6].location}
      />
        <StudentCard
        name={students[7].name}
        image={students[7].image}
        occupation={students[7].occupation}
        location={students[7].location}
      />
        <StudentCard
        name={students[8].name}
        image={students[8].image}
        occupation={students[8].occupation}
        location={students[8].location}
      />
        <StudentCard
        name={students[9].name}
        image={students[9].image}
        occupation={students[9].occupation}
        location={students[9].location}
      />
        <StudentCard
        name={students[10].name}
        image={students[10].image}
        occupation={students[10].occupation}
        location={students[10].location}
      />
        <StudentCard
        name={students[11].name}
        image={students[11].image}
        occupation={students[11].occupation}
        location={students[11].location}
      />
        <StudentCard
        name={students[12].name}
        image={students[12].image}
        occupation={students[12].occupation}
        location={students[12].location}
      />
        <StudentCard
        name={students[13].name}
        image={students[13].image}
        occupation={students[13].occupation}
        location={students[13].location}
      />
        <StudentCard
        name={students[14].name}
        image={students[14].image}
        occupation={students[14].occupation}
        location={students[14].location}
      />
        <StudentCard
        name={students[15].name}
        image={students[15].image}
        occupation={students[15].occupation}
        location={students[15].location}
      />
        <StudentCard
        name={students[16].name}
        image={students[16].image}
        occupation={students[16].occupation}
        location={students[16].location}
      />
        <StudentCard
        name={students[17].name}
        image={students[17].image}
        occupation={students[17].occupation}
        location={students[17].location}
      />
        <StudentCard
        name={students[18].name}
        image={students[18].image}
        occupation={students[18].occupation}
        location={students[18].location}
      />
        <StudentCard
        name={students[19].name}
        image={students[19].image}
        occupation={students[19].occupation}
        location={students[19].location}
      />
        <StudentCard
        name={students[20].name}
        image={students[20].image}
        occupation={students[20].occupation}
        location={students[20].location}
      />
        <StudentCard
        name={students[21].name}
        image={students[21].image}
        occupation={students[21].occupation}
        location={students[21].location}
      />
        <StudentCard
        name={students[22].name}
        image={students[22].image}
        occupation={students[22].occupation}
        location={students[22].location}
      />
        <StudentCard
        name={students[23].name}
        image={students[23].image}
        occupation={students[23].occupation}
        location={students[23].location}
      />
        <StudentCard
        name={students[24].name}
        image={students[24].image}
        occupation={students[24].occupation}
        location={students[24].location}
      />
        <StudentCard
        name={students[25].name}
        image={students[25].image}
        occupation={students[25].occupation}
        location={students[25].location}
      />
        <StudentCard
        name={students[26].name}
        image={students[26].image}
        occupation={students[26].occupation}
        location={students[26].location}
      />
        <StudentCard
        name={students[27].name}
        image={students[27].image}
        occupation={students[27].occupation}
        location={students[27].location}
      />
    </Wrapper>
  );
}

export default App;
